### ISSUE TITLE
Get List Not Returning Custom Fields

### ISSUE THREAD

**Issue by billystalnaker** [Intacct/intacct-sdk-php#101]
I am trying to get all fields from the project object including my custom fields. But I do not see them in my results for the get_list response. Any help would be appreciated.

		$list = new GetList();
		$list->setObjectName($object_name);
		if(count($keys) == 1)
		{
			$key = array_shift($keys);
			$main_filter = new ExpressionFilter();
			$main_filter->setFieldName($object_id);
			$main_filter->setOperator('=');
			$main_filter->setValue($key);
		}
		else
		{
			$main_filter = new LogicalFilter();
			$main_filter->setOperator('or');
			$filters = [];
			foreach($keys as $key)
			{
				$filter = new ExpressionFilter();
				$filter->setFieldName($object_id);
				$filter->setOperator('=');
				$filter->setValue($key);
				$filters[] = $filter;
			}
			$main_filter->setFilters($filters);
		}
		$list->setControlId($object_name . '-list-' . Crypto::getRandomKey(10));
		$list->setFilters([$main_filter]);

		$content = new Content([$list]); //Wrap that GetList (and other FunctionInterfaces) within a Content class
		$response = self::$client->execute($content, false, Crypto::getRandomKey(24)); //Call our client to execute that Content
		$result = $response->getOperation()->getResult(); //From the response, get the result out of the Operation
		$result->ensureStatusSuccess();

**Comment by jimmymcpeter** [comment]
I don't think this is an issue with the SDK, but an issue with the API function itself. It might not support returning custom fields for that object. You'd be better off using readByQuery in my opinion

On Apr 18, 2017 4:54 AM, billystalnaker <notifications@github.com> wrote:

I am trying to get all fields from the project object including my custom fields. But I do not see them in my results for the get_list response. Any help would be appreciated.

        $list = new GetList();
        $list->setObjectName($object_name);
        if(count($keys) == 1)
        {
                $key = array_shift($keys);
                $main_filter = new ExpressionFilter();
                $main_filter->setFieldName($object_id);
                $main_filter->setOperator('=');
                $main_filter->setValue($key);
        }
        else
        {
                $main_filter = new LogicalFilter();
                $main_filter->setOperator('or');
                $filters = [];
                foreach($keys as $key)
                {
                        $filter = new ExpressionFilter();
                        $filter->setFieldName($object_id);
                        $filter->setOperator('=');
                        $filter->setValue($key);
                        $filters[] = $filter;
                }
                $main_filter->setFilters($filters);
        }
        $list->setControlId($object_name . '-list-' . Crypto::getRandomKey(10));
        $list->setFilters([$main_filter]);

        $content = new Content([$list]); //Wrap that GetList (and other FunctionInterfaces) within a Content class
        $response = self::$client->execute($content, false, Crypto::getRandomKey(24)); //Call our client to execute that Content
        $result = $response->getOperation()->getResult(); //From the response, get the result out of the Operation
        $result->ensureStatusSuccess();

**Comment by billystalnaker** [comment]
@jimmymcpeter If I'm using the ReadByQuery how can I write a `projectid IN(1,2,3,...)` query?

**Comment by billystalnaker** [comment]
:1st_place_medal: haha Doing a little research I found this: https://developer.intacct.com/wiki/readbyquery That looks like it will work beautifully. Thanks!
