### ISSUE TITLE
Unit of Measure accessibility

### ISSUE THREAD

**Issue by billystalnaker** [Intacct/intacct-sdk-php#103]
I can't seem to find the ability to manipulate Unit of Measures in the Intacct SDK

**Comment by jimmymcpeter** [comment]
We never added it because they're barely used.  For now you'll need to write your own to the `UOM` and `UOMDETAIL` objects.

**Comment by billystalnaker** [comment]
Thanks!

**Comment by jimmymcpeter** [comment]
PS we accept pull requests ;-)

**Comment by billystalnaker** [comment]
I'm looking here: https://developer.intacct.com/wiki/unit-measure-detail-development-functions and don't see much detail on the detail. I'm not sure of the name of the integration fields. Can you help me on this, and I'll gladly create a pull request.

**Comment by jimmymcpeter** [comment]
Sorry I missed your reply. Unit of Measure hasn't been certified yet for use with the create/update functions so I'm not sure how well it will work.  If you have a dev company with platform enabled, you can view all of the object's fields by navigating to Platform Services > Objects > List and then clicking on Unit of Measure Detail -- here are a few

| Field | Type | Integration Name |
| --- | --- | --- |
| Abbreviation | Text (30) | ABBREVIATION |
| Decimals | Integer | NUMDECIMALS |
| Is Base | Check Box | ISBASE |
| Record Number | Integer | RECORDNO |
| Unit | Record Name | UNIT |
| Unit Group | Integer | GRPKEY |
