### ISSUE TITLE
Abstract Item missing Item Type

### ISSUE THREAD

**Issue by billystalnaker** [Intacct/intacct-sdk-php#107]
I can't seem to find Item Type anywhere in the class objects, am I missing something?

**Comment by jimmymcpeter** [comment]
It's set on create and becomes unchangeable -- we should probably add the values as constants or something in there but they are listed here..  https://developer.intacct.com/api/inventory-control/items/#create-item

Item type. Use `Inventory`, `Non-Inventory`, `Non-Inventory (Purchase only)`, `Non-Inventory (Sales only)`, `Kit`, or `Stockable Kit`

**Comment by jimmymcpeter** [comment]
It's hiding in the ItemCreate class

**Comment by billystalnaker** [comment]
Ah, I see!
