### ISSUE TITLE
SODOCUMENTENTRY STATE is always NULL

### ISSUE THREAD

**Issue by billystalnaker** [Intacct/intacct-sdk-php#119]
I'm not sure if I should be asking this here, or in the developer community. But the `STATE` field on the `SODOCUMENTENTRY` object is always `NULL` regardless of whether the `SODOCUMENT` has been converted, partially converted or changed to any other state. Is this normal behavior?

**Comment by jimmymcpeter** [comment]
Yeah this is a product issue.  You can try asking on the community, but you might also ask support.

**Comment by billystalnaker** [comment]
Thanks
