### ISSUE TITLE
Invoice GL Posting Date

### ISSUE THREAD

**Issue by leimd** [Intacct/intacct-sdk-php#133]
Hello,

We ran into a issue when posting invoice using the SDK.
The problem is that the invoice's GL posting date is not populating in our client's Intacct instance even though the glPostingDate is set explicitlym our code using the following code snippet:

```php
...
$billCreate = new BillCreate();
$billCreate->setGlPostingDate(self::getDateType($export->getPostMonth()));
...
```

The strange thing is that this works perfectly fine on our dev Intacct instance, but it does not work on our client's Intacct instance.

Unfortunately we are stuck version 1.0.7 of the sdk because the application is running in PHP 5.6, and upgrading to PHP 7 is not going happen any time soon. This means the BillCreate here is using the legacy BillCreate.

Any insights into why this is happening would be greatly appreciated. 

Thanks.

**Comment by jimmymcpeter** [comment]
I would double check your client's company has allow GL posting date overrides on the bill enabled.

I'm also curious what your code `self::getDateType($export->getPostMonth())` evaluates to.  Are you able to use xdebug to look at this, or write it to a log file?  The SDK has monolog support built-in so you can log the XML request, an example is in one of the tests here - https://github.com/Intacct/intacct-sdk-php/blob/1.0/test/Intacct/IntacctClientTest.php#L318

**Comment by leimd** [comment]
Hi Jimmy,

I was able to verify that their Overriding GL Posting date setting is turned on. 

![image](https://user-images.githubusercontent.com/5065625/38448742-ace36986-39bb-11e8-85b4-43326f19be52.png)

`self::getDateType` would take a PHP DateTime and return an instance of DateType for Intacct.

For logging ,we've only added logging for Intacct SDK recently, so maybe when I have more logs, it will be easier to debug. 

Could you think of another settings that would affect this ? This functionality works on our dev Intacct instance, but not on the client's Intacct which leads us to believe there might be a setting somewhere that's preventing setting the GL posting date.

Regards,
Tom

**Comment by jimmymcpeter** [comment]
> Could you think of another settings that would affect this ? This functionality works on our dev Intacct instance, but not on the client's Intacct which leads us to believe there might be a setting somewhere that's preventing setting the GL posting date.

You would normally get an API error message back if some config was preventing it.  I think you're going to have to log the request/response to really verify this.

**Comment by leimd** [comment]
Hi Jimmy,

It turned out to be a setting on our software that was preventing sending the post date. 

Thank you for your help!

Tom
