### ISSUE TITLE
Location ID / Multi-entity

### ISSUE THREAD

**Issue by jaredtking** [Intacct/intacct-sdk-php#135]
Does this library support setting the login location ID? I was not able to find any mentions of it anywhere throughout the code base. Is there a code sample for connecting to a multi-entity Intacct account?

**Comment by jimmymcpeter** [comment]
You have to use the pipe character to concatenate them described in the `Client/entity slide-in credentials` section [here](https://developer.intacct.com/tools/sdk-php/#credentials)


Description | Company ID
-- | --
Client linked from your console | `myConsoleId\|clientCompanyId`
Entity level of a company | `companyId\|entityId`
Entity level of a company for a client linked from your console | `myConsoleId\|clientCompanyId\|entityId`

**Comment by jaredtking** [comment]
James, this worked perfectly. I missed that in the documentation. You can close this issue. Thank you for your help!
