### ISSUE TITLE
Not Found PurchasingTransactionUpdate class

### ISSUE THREAD

**Issue by HoangDang2589** [Intacct/intacct-sdk-php#136]
Hi, I want to update a Purchase Order like in this document: https://developer.intacct.com/api/purchasing/purchasing-transactions/#update-purchasing-transaction-legacy

but I could not find the Update class. It's only has Create and Delete

**Comment by jimmymcpeter** [comment]
@HoangDang2589, what do you mean by updating a PO link?  If you logged into the UI, where/how would you do this field update?

**Comment by HoangDang2589** [comment]
Sorry for the typo. I mean I want to update a Purchase Order by using PurchasingTransactionUpdate class like when I update OrderEntry by using OrderEntryTransactionUpdate class.

**Comment by jimmymcpeter** [comment]
No worries! We're adding this for the SDK in .NET so we'll look at doing the same for the PHP one

**Comment by HoangDang2589** [comment]
Thanks for reply and I need PurchasingTransactionLineUpdate too.

**Comment by jimmymcpeter** [comment]
> Update a Sale Quote Transaction

Take a look at the unit tests [here](https://github.com/Intacct/intacct-sdk-php/tree/master/test/Intacct/Functions/OrderEntry).  These will give you some examples as well as the output xml being tested against.

> If I only use OrderEntryTransactionLineCreate, It would remove all existed lines. Right?

No, it would add that line to the others.

> And how to load TransactionLine detail of a transaction?

Check out this line in the [test](https://github.com/Intacct/intacct-sdk-php/blob/master/test/Intacct/Functions/OrderEntry/OrderEntryTransactionLineCreateTest.php#L142)

**Comment by HoangDang2589** [comment]
Thanks for your respone. How can I delete an item in a TransactionLine???
