### ISSUE TITLE
Set ITEMGLGROUP not response correct

### ISSUE THREAD

**Issue by HoangDang2589** [Intacct/intacct-sdk-php#139]
Hi,   
I use `setInventoryGlAccountNo('number account');` to set Inventory GL account to Item when creating (` \Intacct\Functions\InventoryControl\ItemCreate`). The item was created successfully but when I query the item it return   
![image](https://user-images.githubusercontent.com/37523892/40054263-73fe4916-586e-11e8-86fe-3f984a26de4d.png)

all item in `ITEMGLGROUP` is empty.  
How I can get GL accounts attached to the item?

**Comment by jimmymcpeter** [comment]
If you login to the UI and view the item, does it show the inventory GL account?  The company may be setup for advanced transaction definitions, which means these GL accounts you set on an item are hidden and configured a different way.
