### ISSUE TITLE
How to set State value of the invoice

### ISSUE THREAD

**Issue by Dhavalptel** [Intacct/intacct-sdk-php#148]
Hi guys, I tried to find out `setState` method inside `Intacct\Functions\AccountsReceivable\AbstractInvoice.php` but there is no method to set state value of the invoice.
Thanks

**Comment by jimmymcpeter** [comment]
Use `setAction` -- `Draft` or `Submit`. (Default: `Submit`)

**Comment by Dhavalptel** [comment]
Okay thanks!
