### ISSUE TITLE
How to set shipping information to invoice?

### ISSUE THREAD

**Issue by Dhavalptel** [Intacct/intacct-sdk-php#149]
Hi, I was able to set `shipTo` but I was unable to find a way to add additional shipping information , Is there any way to set `shippingAddress, shipPhoneNumber, shipCity, shipCompanyName, ShipPostalCode, ShipState, ShipCountry` etc..
Thanks

**Comment by jimmymcpeter** [comment]
You would have that information on an new/existing contact, and then use `setShipToContactName` on the invoice

**Comment by jimmymcpeter** [comment]
`Intacct\Functions\Company\ContactCreate` and `Intacct\Functions\Company\ContactUpdate` are two included functions
