### ISSUE TITLE
Kit Builds via API

### ISSUE THREAD

**Issue by evelynstraight** [Intacct/intacct-sdk-php#157]
Hi, I see in the php sdk documentation there is the ability to build kits from the api.  However, I don't see any functionality in the library - 
https://developer.intacct.com/api/inventory-control/inventory-transactions/#create-build--disassemble-kit-transaction-legacy

Has this been removed or replaced by something else?  Any help would be greatly appreciated.

Thanks.
Evelyn

**Comment by evelynstraight** [comment]
I realized that this code doesn't look to have been written/implemented yet.   Attached are 4 class files that add the ability to create kit builds.   Please feel free to add if desired.

[Kit Build Code.zip](https://github.com/Intacct/intacct-sdk-php/files/4717601/Kit.Build.Code.zip)


Thanks.

**Comment by intacctcoleenho** [comment]
Does this need to be added to the SDK or just to the API documentation?

**Comment by evelynstraight** [comment]
Needs to be added to the SDK.   The api documentation looks to already exist.

Thanks.



[http://maplehill.com/wp-content/uploads/2019/11/mh_signature_logo-1.png]

 Evelyn Straight
  VP Information Technology & Business Optimization
  c: 847.533.4464


  Kinderhook, NY
  maplehillcreamery.com
  [cid:facebook-logo_ba292b92-0a29-47a6-8e9e-57ef65c6f908.png] <https://www.facebook.com/MapleHillCreamery>  [cid:instagram-logo_5d615c98-e4e0-4e5d-9faf-c8252130faea.png] <https://www.instagram.com/maplehillcreamery>  [cid:pinterest_683b942b-0eee-42a9-b047-019dcaaab99f.png] <https://www.pinterest.com/maplehillcreamery>  [cid:twitter_8eaa9602-b8db-453c-b9c1-db6439b4f477.png] <https://www.twitter.com/maplehillcreamery>
DISCLAIMER: This electronic mail message and any attached files contain information intended for the exclusive use of the intended addressee and may contain information that is proprietary, privileged, confidential and/or exempt from disclosure under applicable law. If you are not the intended recipient, you are hereby notified that any viewing, copying, disclosure or distribution of this information may be subject to legal restriction or sanction. Please notify sender if you are an unintended recipient and delete the original message without making copies. Thank you.

**Comment by intacctcoleenho** [comment]
Could you or your team submit a pull request with your changes?  Thanks!
