### ISSUE TITLE
Create/Update within same Content Block

### ISSUE THREAD

**Issue by billystalnaker** [Intacct/intacct-sdk-php#88]
I'm working with the php sdk to interact with Intacct programmatically. That's easy. But I was wondering if there is a way to Create an Intacct object if it doesn't exist by the key I provide? Sort of how DTD 2.1 works with the create_customer function and passing in the CONTACTNAME to create or use that contact. Currently I have to query Intacct, then determine if I get a result back to create/update. Thanks in advance!

**Comment by intacctcoleenho** [comment]
Hi billystalnaker,
A couple questions:
1. Do you mind posting your code? or outline which function class you are trying to use?  I'm assuming you are trying to use https://intacct.github.io/intacct-sdk-php/Intacct/Functions/AccountsReceivable/CustomerCreate.html.
2. What do you mean "key you provide"? Do you mean RECORDNO (i.e. Primary Key) of the CONTACT record? 
Thanks!

**Comment by jpcampbell** [comment]
I think He is asking for upsert. 

Take care,
jpc

**Comment by billystalnaker** [comment]
Here is my query creation:

 ```
		$does_intacct_customer_exist = self::$client->locationExists($location);
		if($does_intacct_customer_exist)
		{
			$query = new ContactUpdate($control);
		}
		else
		{
			$query = new ContactCreate($control);
		}
		$query->setContactName($intacct_location_id);
		$query->setCompanyName($location->getStoreNumber());
		$query->setPrintAs($location->getClientInformation());
		$query->setAddressLine1($location->address);
		$query->setCity($location->city);
		$state = $location->getState();
		if($state instanceof State)
		{
			$query->setStateProvince($state->state_alt_abbr);
			$query->setCountry($state->country);
		}
		else
		{
			$query->setStateProvince('NO STATE SET');
			$query->setCountry('NO COUNTRY SET');
		}
		$query->setZipPostalCode($location->postal_code);
```

My "locationExists" function looks like this:
```
 public function recordExists(IntacctInterface $object)
	{
		$readByQuery = new ReadByQuery(Crypto::getRandomKey(24));    //It's helpful to have a unique controlId passed into the
		//ReadByQuery class for retrieving info encase of errors
		$readByQuery->setObjectName($object::getIntacctObject());  //Yup, we're querying for a CUSTOMER
		$readByQuery->setQuery($object::getIntacctKeyName() . ' = ' . $object->getIntacctKey()); //Here's our query
		//$readByQuery->setPageSize(1);
		$readByQuery->setFields(['*']);

		$content = new Content([$readByQuery]); //Wrap that ReadByQuery (and other FunctionInterfaces) within a Content class

		$response = $this->execute($content, false, Crypto::getRandomKey(24)); //Call our client to execute that Content
		$result = $response->getOperation()->getResult(); //From the response, get the result out of the Operation
		$result->ensureStatusSuccess();
		//And then parse out the results (which are in XML)
		$totalCount = $result->getTotalCount();
		if($totalCount == 0)
		{
			return false;
		}
		return true;
	}
```

So I am using the "CustomerCreate/CustomerUpdate" classes. and I not using the RECORDNO attribute but rather the uniquer key for my system.
"Upsert" sounds like a combination of an Update an dInsert, so if that's the case, please point me in the right direction :smile:

**Comment by jpcampbell** [comment]
Upsert is something you have to do on your own with multiple queries as you have described. It's not a supporter API. 

Take care,
jpc

**Comment by jimmymcpeter** [comment]
Yes upsert is not something native to the Intacct API.  I looked at doing this awhile back in the SDK and extending the Intacct\FieldTypes\Record class to be used with the Intacct\Functions\Common\Create and Intacct\Functions\Common\Update classes.  We decided that passing a huge array of crap is not something we want to encourage.  I'm still on the fence of actually just removing those 3 classes entirely from the SDK.  This would force you to implement Intacct\Functions\FunctionInterface (or extend Intacct\Functions\AbstractFunction) for any functions on standard/custom objects outside of what the SDK provides.

**Comment by billystalnaker** [comment]
Sounds good so, currently, the multiple query way is the only way to accomplish this?

**Comment by jimmymcpeter** [comment]
> Sounds good so, currently, the multiple query way is the only way to accomplish this?

Yes, that's correct

**Comment by billystalnaker** [comment]
Thanks for the help!
