### ISSUE TITLE
Add FilterInterface for ReadByQuery

### ISSUE THREAD

**Issue by jimmymcpeter** [Intacct/intacct-sdk-php#91]
We did this for `get_list` - https://github.com/Intacct/intacct-sdk-php/tree/master/src/Intacct/Functions/Common/GetList

We should add something similar to build the `<query>` block for the dev when they want to use `readByQuery`

query parameter: A subset of standard SQL where clause.  The following SQL operators are supported: `<`, `>`, `>=`, `<=`, `=`, `LIKE`, `NOT LIKE`, `IN`, `NOT IN`, `IS NOT NULL`, `IS NULL`. Multiple fields may be matched using the `AND` and `OR` operators. Joins are not supported. If the value you are filtering on contains an apostrophe, add a backslash before it to escape the apostrophe. For example, to filter on `Erik's Deli` in contacts, your query element would be: `contactname = 'Erik\'s Deli'`

Looking for `!=` operator?  Prefix with `NOT` for example `NOT contactname = 'Erik\'s Deli'`

Requested from issue #90

**Comment by jimmymcpeter** [comment]
@billystalnaker take a look at the query branch I just setup. There's a QueryInterface in there we're considering for v1.1 release.  Check out some of the tests to see the usage

```php
$condition = new GreaterThanOrEqualToInteger();
$condition->setField('RECORDNO');
$condition->setValue(1234);
$readByQuery = new ReadByQuery('unittest');
$readByQuery->setObjectName('CUSTOMER');
$readByQuery->setQuery($condition);
```

If folks want to manually write their own query strings, they're forced into the interface. The same above can be done through the QueryString class:
```php
$readByQuery = new ReadByQuery('unittest');
$readByQuery->setObjectName('CUSTOMER');
$readByQuery->setQuery(new QueryString('RECORDNO >= 1234'));
```

An example of nested conditions -- https://github.com/Intacct/intacct-sdk-php/blob/query/test/Intacct/Functions/Common/Query/Logical/OrConditionTest.php#L86-L114

**Comment by billystalnaker** [comment]
That's awesome. I'm out of town for two weeks. But I will check it out when I get back! Thanks!
