### ISSUE TITLE
Setting IsoCountryCode

### ISSUE THREAD

**Issue by billystalnaker** [Intacct/intacct-sdk-php#92]
Trying to set the isocountrycode xml attribute for a CONTACT object through the sdk, but I can't seem to find the function. Am I missing something?

**Comment by jimmymcpeter** [comment]
Looks like we never put it in there as a getter/setter.  I know if you set the country to "United States" Intacct will set the ISO code for you to "US".  We can add it if you need it though

**Comment by billystalnaker** [comment]
What about if I set the IsoCountryCode, will it set the country to the correct country?

**Comment by jimmymcpeter** [comment]
> What about if I set the IsoCountryCode, will it set the country to the correct country?

Yes

```xml
<create>
    <CONTACT>
        <CONTACTNAME>hello</CONTACTNAME>
        <PRINTAS>world</PRINTAS>
        <MAILADDRESS>
            <COUNTRYCODE>US</COUNTRYCODE>
        </MAILADDRESS>
    </CONTACT>
</create>
```
will result in a contact created with
```xml
<CONTACT>
    <RECORDNO>52</RECORDNO>
    <CONTACTNAME>hello</CONTACTNAME>
    <PRINTAS>world</PRINTAS>
    ...
    <MAILADDRESS>
        ...
        <COUNTRY>United States</COUNTRY>
        <COUNTRYCODE>US</COUNTRYCODE>
        ...
    </MAILADDRESS>
    ...
</CONTACT>
```

**Comment by billystalnaker** [comment]
Yes, that would be best, as I have Country ISO Codes stored in my database, not their names. Thanks!
